name: Build Workflow
on: [push]
jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Step
        run: ./gradlew clean build

